# Generated by Django 5.2.8 on 2026-05-16 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['name']},
        ),
    ]
