# Generated by Django 5.2.8 on 2026-03-10 18:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_salesreport_remove_useractivity_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='productview',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='average_order_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='total_customers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='total_orders',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
