# Generated by Django 5.2.8 on 2026-03-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_pageview_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productview',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
