# Generated by Django 5.2.8 on 2026-05-16 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_productview_ip_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesreport',
            options={'ordering': ['-report_date']},
        ),
    ]
