# Generated by Django 5.2.7 on 2025-10-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='is_billing',
        ),
        migrations.RemoveField(
            model_name='address',
            name='is_shipping',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state_province',
        ),
        migrations.RemoveField(
            model_name='address',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(default='shipping', max_length=50),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
