# Generated by Django 5.2.7 on 2025-12-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='postal_code',
            field=models.CharField(default='00000', max_length=20),
            preserve_default=False,
        ),
    ]
