# Generated by Django 5.2.7 on 2025-10-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingmethod',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
