# Generated by Django 5.2.8 on 2026-05-16 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'ordering': ['name'], 'verbose_name_plural': 'Order Statuses'},
        ),
    ]
